workflows:
  android-workflow:
    name: Build SquidInjector APK
    environment:
      vars:
        PACKAGE_NAME: "com.squid.injector"
        APP_NAME: "SquidInjector"
      android: latest
    scripts:
      - name: Download .so file from Google Drive
        script: |
          echo "Downloading libil2cpp.so..."
          curl -L -o ./libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
          echo "Downloaded libil2cpp.so"

      - name: Verify global-metadata.dat
        script: |
          if [ ! -f ./global-metadata.dat ]; then
            echo "Error: global-metadata.dat not found in root directory!"
            exit 1
          else
            echo "global-metadata.dat found."
          fi

      - name: Setup Gradle Wrapper
        script: |
          chmod +x ./gradlew

      - name: Build APK (Debug)
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
