workflows:
  android-workflow:
    name: Android Workflow
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk/jdk11
    scripts:
      - name: Decode gradle-wrapper.jar
        script: |
          echo "Decoding gradle-wrapper.jar from base64"
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
