workflows:
  android-workflow:
    name: SquidInjector
    environment:
      vars:
        PACKAGE_NAME: "com.squidgame.unleashed"
      java: 17
      android: true
    scripts:
      - echo "Step 1: Downloading .so file from Google Drive"
      - curl -L -o libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"

      - echo "Step 2: Decoding gradle-wrapper.jar from base64"
      - mkdir -p gradle/wrapper
      - base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
      - chmod +x gradle/wrapper/gradle-wrapper.jar

      - echo "Step 3: Make gradlew executable"
      - chmod +x ./gradlew

      - echo "Step 4: Build APK"
      - ./gradlew assembleDebug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
