workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Step 1 - Download gradle-wrapper.jar
        script: |
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip -j gradle/wrapper/gradle-wrapper.jar 'gradle-*/lib/gradle-wrapper.jar' -d gradle/wrapper/
      - name: Step 2 - Prepare gradlew permissions
        script: |
          chmod +x ./gradlew
      - name: Step 3 - Download .so file
        script: |
          curl -L -o ./libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      - name: Step 4 - Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
