workflows:
  android-workflow:
    name: Android Build Workflow
    environment:
      vars:
        JAVA_HOME: $CM_JAVA_HOME
    scripts:
      - name: Download .so file from Google Drive
        script: |
          echo "Downloading libil2cpp.so from Google Drive"
          curl -L -o libil2cpp.so 'https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY'
      - name: Move .so file to libs directory
        script: |
          mkdir -p android/app/src/main/jniLibs/armeabi-v7a
          mv libil2cpp.so android/app/src/main/jniLibs/armeabi-v7a/
      - name: Verify .so file
        script: |
          ls -lh android/app/src/main/jniLibs/armeabi-v7a/
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
