workflows:
  SquidInjector:
    name: SquidInjector
    scripts:
      - name: Step 1 - Download Gradle 7.2
        script: |
          curl -LO https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip gradle-7.2-bin.zip
          chmod +x gradle-7.2/bin/gradle
      - name: Step 2 - Download .so file
        script: |
          mkdir -p app/libs
          curl -L -o app/libs/libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      - name: Step 3 - Build APK
        script: |
          gradle-7.2/bin/gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
