workflows:
  android-workflow:
    name: SquidInjector
    scripts:
      - name: Step 1 - Download Gradle 7.2
        script: |
          echo "Downloading Gradle 7.2..."
          curl -L -o gradle.zip https://downloads.gradle-dn.com/distributions/gradle-7.2-bin.zip
          unzip gradle.zip
          chmod +x gradle-7.2/bin/gradle

      - name: Step 2 - Download .so file
        script: |
          echo "Downloading .so file..."
          mkdir -p app/libs
          curl -L -o app/libs/libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"

      - name: Step 3 - Build APK
        script: |
          echo "Building APK..."
          export JAVA_HOME=/opt/java/openjdk-17
          ./gradle-7.2/bin/gradle assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
