workflows:
  SquidInjector:
    name: SquidInjector
    environment:
      android: true
      vars:
        JAVA_HOME: /opt/android/openjdk-17
    scripts:
      - name: Print environment
        script: |
          echo "JAVA_HOME: $JAVA_HOME"
      - name: Download .so file from Google Drive
        script: |
          echo "Downloading libil2cpp.so from Google Drive..."
          file_id="1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
          curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${file_id}" > temp.html
          confirm_code=$(awk '/confirm=/{print $NF}' temp.html | sed 's/.*confirm=.*&amp;.*/\1/')
          curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=${confirm_code}&id=${file_id}" -o app/src/main/jniLibs/armeabi-v7a/libil2cpp.so
          echo "Download complete!"
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
