workflows:
  android-workflow:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Step 1 - Download fresh gradlew and wrapper jar + properties
        script: |
          mkdir -p gradle/wrapper
          curl -o gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew
          curl -o gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/7.2/gradle-wrapper-7.2.jar
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-7.2-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
      - name: Step 2 - Download .so file
        script: |
          curl -L -o ./libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      - name: Step 3 - Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
