workflows:
  SquidInjector:
    name: SquidInjector
    environment:
      vars:
        JAVA_HOME: /opt/android/openjdk
    scripts:
      - name: Decode gradle-wrapper.jar
        script: |
          echo "Decoding gradle-wrapper.jar from base64"
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Download .so file from Google Drive
        script: |
          echo "Downloading libil2cpp.so from Google Drive"
          wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY' -O libil2cpp.so
      - name: Build APK
        script: |
          echo "Building APK manually"
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
