workflows:
  android-workflow:
    name: Android Workflow
    environment:
      java: 11
    scripts:
      - name: Download libil2cpp.so
        script: |
          echo "Downloading libil2cpp.so from Google Drive"
          wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY' -O libil2cpp.so
      - name: Decode gradle-wrapper.jar
        script: |
          echo "Decoding gradle-wrapper.jar from base64"
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
