workflows:
  SquidInjector:
    name: SquidInjector
    environment:
      android: true
      vars:
        JAVA_HOME: /opt/java/openjdk-17
    scripts:
      - |
        echo "Step 1 - Prepare gradlew permissions"
        chmod +x ./gradlew

      - |
        echo "Step 2 - Download .so file from Google Drive"
        curl -L -o ./app/src/main/jniLibs/libil2cpp.so 'https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY'

      - |
        echo "Step 3 - Build APK"
        ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
