workflows:
  SquidInjector:
    name: SquidInjector
    environment:
      vars:
        JAVA_HOME: /opt/android/java/openjdk-17
    scripts:
      - name: Step 1 - Prepare gradlew permissions
        script: |
          chmod +x gradlew
      - name: Step 2 - Download .so file
        script: |
          curl -o app/libs/libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      - name: Step 3 - Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
