workflows:
  android-workflow:
    name: SquidInjector Build
    environment:
      vars:
        JAVA_HOME: /opt/android/java/openjdk-17
    scripts:
      - echo "Step 1 - Download gradle-wrapper.jar"
      - mkdir -p gradle/wrapper
      - curl -L -o gradle/wrapper/gradle-wrapper.jar "https://raw.githubusercontent.com/your-repo-path/gradle-wrapper.jar"

      - echo "Step 2 - Prepare gradlew permissions"
      - chmod +x ./gradlew

      - echo "Step 3 - Download .so file"
      - mkdir -p app/libs
      - curl -L -o app/libs/libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"

      - echo "Step 4 - Build APK"
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
