workflows:
  SquidInjector:
    name: SquidInjector
    environment:
      vars:
        SO_FILE_URL: "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      java: 11
    scripts:
      - name: Install Gradle
        script: |
          sudo apt-get update
          sudo apt-get install wget unzip -y
          wget https://services.gradle.org/distributions/gradle-7.2-bin.zip
          unzip gradle-7.2-bin.zip
          export PATH=$PWD/gradle-7.2/bin:$PATH
          gradle -v
      - name: Download .so file
        script: |
          wget -O libil2cpp.so "$SO_FILE_URL"
      - name: Move .so file to assets
        script: |
          mkdir -p app/src/main/assets
          mv libil2cpp.so app/src/main/assets/
      - name: Decode gradle-wrapper.jar
        script: |
          mkdir -p gradle/wrapper
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
