workflows:
  android-workflow:
    name: SquidInjector Build
    environment:
      android: latest
      java: 17
    scripts:
      - echo "Step 1 - Prepare gradlew permissions"
      - chmod +x ./gradlew

      - echo "Step 2 - Download gradle-wrapper.jar"
      - mkdir -p gradle/wrapper
      - curl -L -o gradle/wrapper/gradle-wrapper.jar "https://github.com/YourUsername/YourRepo/raw/main/gradle-wrapper.jar"

      - echo "Step 3 - Download .so file"
      - mkdir -p app/libs
      - curl -L -o app/libs/libil2cpp.so "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"

      - echo "Step 4 - Build APK"
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
