workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk
      android: true
    scripts:
      - name: Install required tools
        script: |
          echo "Installing zip and base64 tools"
          apt-get update
          apt-get install -y zip coreutils

      - name: Decode gradle-wrapper.jar
        script: |
          echo "Decoding gradle-wrapper.jar from base64"
          base64 --decode -i gradle/wrapper/gradle-wrapper.jar.base64 -o gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Make gradlew executable
        script: |
          chmod +x gradlew

      - name: Download libil2cpp.so from Google Drive
        script: |
          echo "Downloading libil2cpp.so from Google Drive"
          file_id="1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
          curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${file_id}" > temp.html
          confirm=$(grep -Po 'confirm=\K[^&]+' temp.html)
          curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=${confirm}&id=${file_id}" -o libil2cpp.so
          rm -f ./cookie temp.html
          echo "Download completed."

      - name: Build APK
        script: |
          echo "Building APK"
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - build/app/outputs/flutter-apk/*.apk
