workflows:
  android-workflow:
    name: SquidInjector
    environment:
      vars:
        GAME_LIB_URL: "https://drive.google.com/uc?export=download&id=1Zbf45fo_52VdkX0xojWRgkTS0jzsX3zY"
      java: 17
    scripts:
      - name: Decode gradle-wrapper.jar
        script: |
          mkdir -p gradle/wrapper
          base64 -d gradle/wrapper/gradle-wrapper.jar.base64 > gradle/wrapper/gradle-wrapper.jar
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Download .so file
        script: |
          curl -L "$GAME_LIB_URL" -o libil2cpp.so
          echo ".so file downloaded."

      - name: Prepare build
        script: |
          chmod +x gradlew
          ./gradlew dependencies

      - name: Build APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
